Auth screen and change Activity Auth -> Main
OnlyOneSocial/AndroidApp pull request #8
Opened 2022-02-28 23:52 UTC by katelinlis

Auth screen and change Activity Auth -> Main
and Work with JWT auth

залила наработки которые успела проверить и протестировать
не успела почистить 
почищу позже и доделаю

взяла готовую реализацию из Android studio

2022-03-01 05:31 UTC, Kamillaova reviewed
перед коммитом делай реформат кода)

2022-03-01 05:31 UTC, Kamillaova commented on app/src/main/java/dev/syorito_hatsuki/onlyone/api/OnlyOneApiImpl.kt
> +    private lateinit var _token: String
зачем _?

2022-03-01 05:31 UTC, Kamillaova commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/MainActivity.kt
> +val onlyOneApi by KoinJavaComponent.inject<OnlyOneApi>(OnlyOneApi::class.java)
https://insert-koin.io/docs/reference/koin-core/koin-component/ 

:((

2022-03-01 10:09 UTC, katelinlis commented on app/src/main/java/dev/syorito_hatsuki/onlyone/api/OnlyOneApiImpl.kt
> +    private lateinit var _token: String
Параметр для сохранения токена

2022-03-01 10:18 UTC, katelinlis commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/MainActivity.kt
> +val onlyOneApi by KoinJavaComponent.inject<OnlyOneApi>(OnlyOneApi::class.java)
Что?

2022-03-01 15:23 UTC, Kamillaova commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/MainActivity.kt
> +val onlyOneApi by KoinJavaComponent.inject<OnlyOneApi>(OnlyOneApi::class.java)
> Что?

read ^

2022-03-02 08:02 UTC, Kamillaova commented on app/src/main/java/dev/syorito_hatsuki/onlyone/api/OnlyOneApi.kt
> +import dev.syorito_hatsuki.onlyone.api.user.get_users.response.*
ааасуждаю такое

2022-03-02 08:06 UTC, Kamillaova requested changes
почему _request - nullable?

2022-03-02 08:06 UTC, Kamillaova commented on app/src/main/java/dev/syorito_hatsuki/onlyone/api/OnlyOneApiImpl.kt
> +        url {
url { encodedPath = "message/im" }, и вообще сделай для этого функцию чтоб не писать это постоянно)

2022-03-02 08:06 UTC, Kamillaova commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/dialogs/DialogFragment.kt
> +    private val binding get() = _binding!!
private val binding get() = _binding ?: error("_binding is null")

2022-03-02 08:06 UTC, Kamillaova commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/dialogs/DialogFragment.kt
> +    private var _binding: FragmentDialogsBinding? = null
А стоп, а зачем он нуллабл?

2022-03-02 19:02 UTC, syorito-hatsuki commented on app/src/main/java/dev/syorito_hatsuki/onlyone/api/OnlyOneApi.kt
> +import dev.syorito_hatsuki.onlyone.api.user.get_users.response.*
Это скорее всего решение IDE

2022-03-06 13:06 UTC, syorito-hatsuki commented on app/build.gradle.kts
>          versionName = "1"
Версион нейм тоже неплохо было бы обновлять....

2022-03-06 13:13 UTC, syorito-hatsuki commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/users/UserListAdapter.kt
>                  memoryCachePolicy(CachePolicy.ENABLED)
А на кеширование мы хрен клали?) Ещё кеширование в Ktor добавь https://stackoverflow.com/a/58150515

2022-03-06 13:13 UTC, syorito-hatsuki commented on app/src/main/java/dev/syorito_hatsuki/onlyone/api/OnlyOneApiImpl.kt
> +
Чё за туева куча пустых пробелов во всём коммите?

2022-03-06 13:16 UTC, syorito-hatsuki commented on app/src/main/java/dev/syorito_hatsuki/onlyone/data/LoginDataSource.kt
> -        // TODO: revoke authentication
TODO("REASON HERE")

2022-03-06 14:00 UTC, katelinlis commented on app/build.gradle.kts
>          versionName = "1"
я обновляю постоянно но не делаю коммиты 
потому что тестирую у себя

2022-03-06 15:43 UTC, katelinlis commented on app/src/main/java/dev/syorito_hatsuki/onlyone/api/OnlyOneApiImpl.kt
> +        url {
пыталась сделать функцию, не работает

2022-03-06 15:43 UTC, katelinlis commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/dialogs/DialogFragment.kt
> +    private var _binding: FragmentDialogsBinding? = null
незнаю :(

2022-03-06 22:47 UTC, Kamillaova commented on app/build.gradle.kts
> +    plugin("kotlin-android")
эээ, apply(plugin = "kotlin-android"), не?

я не особо уверена, что тут не подхватился apply из котлин стдлиба)

2022-03-06 22:49 UTC, syorito-hatsuki commented on app/build.gradle.kts
> +    plugin("kotlin-android")
Нахуй там вообще эплай если сверху массив куда их кидать 😂

2022-03-07 01:03 UTC, katelinlis commented on app/build.gradle.kts
> +    plugin("kotlin-android")
Автоматическое изменение, исправлю

2022-03-07 17:59 UTC, syorito-hatsuki commented on app/src/main/res/layout/fragment_blank.xml
> +                    android:hint="@string/EnterMessage"
id пишутся в lowerCase

2022-03-07 17:59 UTC, syorito-hatsuki commented on app/src/main/res/values/strings.xml
> +    <string name="_0">0</string>
А. Н.А.Х.У.Я

2022-03-08 10:26 UTC, katelinlis commented on app/src/main/res/values/strings.xml
> +    <string name="_0">0</string>
что нахуя?

2022-03-08 21:42 UTC, syorito-hatsuki commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/fragments/UserProfileFragment.kt
> +import dev.syorito_hatsuki.onlyone.databinding.FragmentUserpageBinding
Page с большой

2022-03-08 21:42 UTC, syorito-hatsuki commented on app/src/main/java/dev/syorito_hatsuki/onlyone/ui/fragments/UserProfileFragment.kt
> +                if (userid == 0){
Проверку такую лучше вынести в ViewModel

2022-03-09 21:30 UTC, Kamillaova commented on app/src/main/res/values/strings.xml
> +    <string name="_0">0</string>
> что нахуя?

ахаххаха

2022-03-13 16:47 UTC, syorito-hatsuki commented
Ты это когда нибудь закроешь?

2022-03-18 17:09 UTC, merged